# .github/workflows/deploy.yml
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'  # Version avec Dart 3.8+
        channel: 'stable'
        cache: true
    
    - name: Flutter doctor
      run: flutter doctor -v
    
    - name: Get dependencies
      run: flutter pub get
    
    # Analyse désactivée temporairement pour le déploiement
    # - name: Analyze code
    #   run: flutter analyze --fatal-warnings
    
    - name: Check formatting
      run: dart format --set-exit-if-changed .
    
    # Décommentez si vous avez des tests
    # - name: Run tests
    #   run: flutter test
    
    - name: Build web
      run: |
        flutter build web \
          --release \
          --base-href "/${{ github.event.repository.name }}/" \
          --web-renderer canvaskit \
          --dart-define=FLUTTER_WEB_CANVASKIT_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/canvaskit/
    
    - name: Add .nojekyll file
      run: touch build/web/.nojekyll
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
